export default {
  LOGOUT: 'LOGOUT',
  LOAD_ME: 'LOAD_ME',
  LOAD_LOGS: 'LOAD_LOGS',
  PAUSE_LOGS: 'PAUSE_LOGS',
  LOAD_LOGS_STATS: 'LOAD_LOGS_STATS',
  LOAD_DASHBOARDS: 'LOAD_DASHBOARDS',
  ADD_DASHBOARD: 'ADD_DASHBOARD'
}
