export default {
  WS_CONNECT: 'WS_CONNECT',
  LOGOUT: 'LOGOUT',
  LOAD_ME: 'LOAD_ME',
  LOAD_LOGS: 'LOAD_LOGS',
  PAUSE_LOGS: 'PAUSE_LOGS',
  LOAD_LOGS_STATS: 'LOAD_LOGS_STATS',
  LOAD_DASHBOARDS: 'LOAD_DASHBOARDS',
  LOAD_SHARED: 'LOAD_SHARED',
  ADD_DASHBOARD: 'ADD_DASHBOARD',
  EDIT_DASHBOARD: 'EDIT_DASHBOARD',
  DELETE_DASHBOARD: 'DELETE_DASHBOARD',
  SHARE_DASHBOARD: 'SHARE_DASHBOARD'
}
