export default {
  SET_JWT: 'SET_JWT',
  UNSET_JWT: 'UNSET_JWT',
  SWITCH_THEME: 'SWITCH_THEME',
  SWITCH_ORIENT: 'SWITCH_ORIENT',
  SWITCH_FULL: 'SWITCH_FULL',
  SWITCH_DIRECTION: 'SWITCH_DIRECTION'
}
