export default {
  SET_JWT: 'SET_JWT',
  UNSET_JWT: 'UNSET_JWT',
  SWITCH_THEME: 'SWITCH_THEME',
  SWITCH_ORIENT: 'SWITCH_ORIENT',
  SWITCH_FULL: 'SWITCH_FULL',
  SWITCH_DIRECTION: 'SWITCH_DIRECTION',
  SET_REDIRECT: 'SET_REDIRECT',
  FLUSH_REDIRECT: 'FLUSH_REDIRECT',
  DELETE_DASHBOARD: 'DELETE_DASHBOARD',
  EDIT_DASHBOARD: 'EDIT_DASHBOARD',
  MEMBER_ADD: 'MEMBER_ADD',
  MEMBER_REMOVE: 'MEMBER_REMOVE',
}
